project_id = "xuxfuonzsfvrirdwzddt"

# Automatic entity discovery - runs every hour
[functions.auto-sync-entities]
verify_jwt = false

[functions.auto-sync-entities.cron]
schedule = "0 * * * *"  # Every hour at minute 0

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.process-jobs]
verify_jwt = false

[functions.aggregate-learnings]
verify_jwt = false

[functions.analyze-memories]
verify_jwt = true

[functions.analyze-traces]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.apply-deltas]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.health-liveness]
verify_jwt = false

[functions.health-readiness]
verify_jwt = false

[functions.generate-event-form]
verify_jwt = true

[functions.rocker-memory]
verify_jwt = true

[functions.rocker-admin]
verify_jwt = true

[functions.rocker-chat]
verify_jwt = true

[functions.rocker-health]
verify_jwt = false

[functions.rocker-proposals]
verify_jwt = true

[functions.consent-status]
verify_jwt = true

[functions.consent-accept]
verify_jwt = true

[functions.consent-revoke]
verify_jwt = true

[functions.entity-lookup]
verify_jwt = true

[functions.generate-preview]
verify_jwt = true

[functions.upload-media]
verify_jwt = true

[functions.save-post]
verify_jwt = true

[functions.unsave-post]
verify_jwt = true

[functions.reshare-post]
verify_jwt = true

[functions.recall-content]
verify_jwt = true

[functions.rocker-voice-session]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.moderate-memory]
verify_jwt = true

[functions.kb-ingest]
verify_jwt = true

[functions.kb-search]
verify_jwt = true

[functions.kb-item]
verify_jwt = true

[functions.kb-related]
verify_jwt = true

[functions.kb-playbook]
verify_jwt = true

[functions.rocker-fetch-url]
verify_jwt = true

[functions.term-lookup]
verify_jwt = true

[functions.bootstrap-super-admin]
verify_jwt = true

[functions.andy-admin]
verify_jwt = true

[functions.promotion-manager]
verify_jwt = true

[functions.chat-store]
verify_jwt = true

