project_id = "xuxfuonzsfvrirdwzddt"

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.process-jobs]
verify_jwt = false

[functions.analyze-traces]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.health-liveness]
verify_jwt = false

[functions.health-readiness]
verify_jwt = false

[functions.generate-event-form]
verify_jwt = true
