project_id = "xuxfuonzsfvrirdwzddt"

[functions.andy-chat]
verify_jwt = true


[functions.andy-embed-knowledge]
verify_jwt = false

[functions.rocker-web-search]
verify_jwt = false

# Automatic entity discovery - runs every hour
[functions.auto-sync-entities]
verify_jwt = false

[functions.auto-sync-entities.cron]
schedule = "0 * * * *"  # Every hour at minute 0

# Process mail outbox - runs every 5 minutes
[functions.process-mail-outbox]
verify_jwt = false

[functions.process-mail-outbox.cron]
schedule = "*/5 * * * *"  # Every 5 minutes

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

# Parallel embedding workers (5 instances)
[functions.generate-embeddings]
verify_jwt = false

[functions.generate-embeddings.cron]
schedule = "*/2 * * * *"

[functions.process-jobs]
verify_jwt = false

[functions.aggregate-learnings]
verify_jwt = false

[functions.analyze-memories]
verify_jwt = true

[functions.analyze-traces]
verify_jwt = false

[functions.generate-suggestions]
verify_jwt = false

[functions.apply-deltas]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.health-liveness]
verify_jwt = false

[functions.health-readiness]
verify_jwt = false

[functions.generate-event-form]
verify_jwt = true

[functions.rocker-memory]
verify_jwt = true

[functions.rocker-admin]
verify_jwt = true

[functions.rocker-organize-knowledge]
verify_jwt = true

[functions.rocker-organize-all]
verify_jwt = true

[functions.rocker-ingest]
verify_jwt = true

[functions.rocker-deep-analyze]
verify_jwt = true

[functions.rocker-reprocess-all]
verify_jwt = true

[functions.rocker-tasks]
verify_jwt = true


[functions.rocker-chat-simple]
verify_jwt = true

[functions.rocker-verify-feature]
verify_jwt = true

[functions.rocker-health]
verify_jwt = false

[functions.rocker-proposals]
verify_jwt = true

[functions.consent-status]
verify_jwt = true

[functions.consent-accept]
verify_jwt = true

[functions.consent-revoke]
verify_jwt = true

[functions.entity-lookup]
verify_jwt = true

[functions.generate-preview]
verify_jwt = true

[functions.upload-media]
verify_jwt = true

[functions.save-post]
verify_jwt = true

[functions.unsave-post]
verify_jwt = true

[functions.reshare-post]
verify_jwt = true

[functions.recall-content]
verify_jwt = true



[functions.moderate-memory]
verify_jwt = true

[functions.kb-ingest]
verify_jwt = true

[functions.kb-search]
verify_jwt = true

[functions.kb-item]
verify_jwt = true

[functions.kb-related]
verify_jwt = true

[functions.kb-playbook]
verify_jwt = true

[functions.rocker-fetch-url]
verify_jwt = true

[functions.term-lookup]
verify_jwt = true

[functions.bootstrap-super-admin]
verify_jwt = true

[functions.andy-admin]
verify_jwt = true

[functions.promotion-manager]
verify_jwt = true

[functions.chat-store]
verify_jwt = true

[functions.rocker-telemetry]
verify_jwt = true

[functions.summarize-thread]
verify_jwt = true

[functions.ai-rank-search]
verify_jwt = true

[functions.ai-curate-feed]
verify_jwt = true

# --- PR2.6 Rocker Tasks (Proactive SMS/Chat) ---
[functions.rocker-send-outbox]
verify_jwt = false

[functions.rocker-send-outbox.cron]
schedule = "* * * * *"  # Every minute

[functions.rocker-sms-webhook]
verify_jwt = false

# --- Phase 3 Preview Pay Functions ---
[functions.preview-pay-checkout]
verify_jwt = true

[functions.preview-pay-labels]
verify_jwt = true

# --- PR-I1 Infrastructure: Feed API with caching ---
[functions.feed-api]
verify_jwt = false

[functions.run-tests]
verify_jwt = true

[functions.auto-pin-business]
verify_jwt = false

# --- Email Inbound Processing ---
[functions.email-inbound]
verify_jwt = false

[functions.process-inbound-email]
verify_jwt = false

# --- Rocker Proactive AI Crons ---
[functions.rocker-daily-tick]
verify_jwt = false

[functions.rocker-daily-tick.cron]
schedule = "0 * * * *"  # Every hour (checks time internally for 9AM/8PM)

[functions.nightly-gap-scan]
verify_jwt = false

[functions.nightly-gap-scan.cron]
schedule = "0 2 * * *"  # Daily at 2 AM

[functions.rocker-proactive-sweep]
verify_jwt = false

[functions.rocker-proactive-sweep.cron]
schedule = "0 */6 * * *"  # Every 6 hours

[functions.nightly-consolidate-notes]
verify_jwt = false

[functions.nightly-consolidate-notes.cron]
schedule = "0 3 * * *"  # Daily at 3 AM

# Capability ranking & decay - runs nightly
[functions.rocker-capability-ranker]
verify_jwt = false

[functions.rocker-web-research]
verify_jwt = false

[functions.rocker-auto-audit]
verify_jwt = false

[functions.rocker-lifecycle-manager]
verify_jwt = false

[functions.rocker-proactive-notifier]
verify_jwt = false

[functions.rocker-capability-ranker.cron]
schedule = "0 4 * * *"  # Daily at 4 AM (after gap scan)

# --- Gemini Second Auditor + KB Functions ---
[functions.rocker-crawl-site]
verify_jwt = true

[functions.rocker-ingest-repo]
verify_jwt = true

[functions.rocker-audit]
verify_jwt = true

[functions.rocker-reembed]
verify_jwt = true


[functions.rocker-audit-system]
verify_jwt = true

[functions.rocker-insights]
verify_jwt = true

# Proactive 30-min autonomous suggestions
[functions.rocker-proactive-30min]
verify_jwt = false

[functions.rocker-proactive-30min.cron]
schedule = "*/30 * * * *"  # Every 30 minutes

[functions.rocker-reembed-all]
verify_jwt = true

# System monitoring - runs every 15 minutes
[functions.rocker-monitor]
verify_jwt = false

[functions.rocker-monitor.cron]
schedule = "*/15 * * * *"  # Every 15 minutes

# AI system health check - public endpoint
[functions.ai_health]
verify_jwt = false

[functions.ai_eventbus]
verify_jwt = false

# AI Control Plane - admin only
[functions.ai_control]
verify_jwt = true

# AI Admin Bind - bootstrap admin
[functions.ai_admin_bind]
verify_jwt = true

# Vendor webhook shims (webhook-lite pattern)
[functions.stripe_webhook]
verify_jwt = false

[functions.twilio_webhook]
verify_jwt = false

# P5: CTM (Conversation Task Memory) workers
[functions.ctm_extract]
verify_jwt = true

[functions.ctm_daily_report]
verify_jwt = true

[functions.ctm_reminder_tick]
verify_jwt = true

# P6: MDR (Multi-Dimensional Reasoning) workers
[functions.mdr_generate]
verify_jwt = true

[functions.mdr_consensus]
verify_jwt = true

# P7: Safety & Autonomy interlocks
[functions.safety_commit_guard]
verify_jwt = true

# P9: Schedulers, Watchdogs, Telemetry
[functions.cron_tick]
verify_jwt = false

[functions.watchdog_tick]
verify_jwt = false

[functions.metrics_export]
verify_jwt = false

[functions.dlq_replay]
verify_jwt = false

# Rate This feedback system
[functions.feedback_rate]
verify_jwt = true

# Super Andy Upgrade - Orchestration & Self-Improvement
[functions.mdr_orchestrate]
verify_jwt = true

[functions.self_improve_tick]
verify_jwt = false

[functions.perceive_tick]
verify_jwt = false

[functions.verify_output]
verify_jwt = true

[functions.model_router]
verify_jwt = true

[functions.federate_share]
verify_jwt = false

[functions.daily_digest_tick]
verify_jwt = false

[functions.circuit_breaker_tick]
verify_jwt = false

# AI Safety & Learning Workers
[functions.red_team_tick]
verify_jwt = false

[functions.red_team_tick.cron]
schedule = "0 2 * * *"  # Daily at 2 AM - bias & drift detection

[functions.user_rag_index]
verify_jwt = false

[functions.user_rag_index.cron]
schedule = "0 */6 * * *"  # Every 6 hours - embeddings generation

[functions.fine_tune_cohort]
verify_jwt = false

[functions.fine_tune_cohort.cron]
schedule = "0 1 * * 1"  # Weekly Monday 1 AM - cohort analysis & tuning proposals

