name: CI - Performance & Accessibility

on:
  pull_request:
    branches: [main, staging]
  push:
    branches: [main, staging]

jobs:
  perf-a11y:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm@9

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Typecheck
        run: pnpm tsc --noEmit

      - name: Build project
        run: pnpm build

      - name: Start preview server
        run: |
          pnpm preview --port 4173 &
          echo $! > preview.pid
          sleep 5

      - name: Accessibility tests (axe-core)
        run: node scripts/a11y-smoke.mjs

      - name: Lighthouse performance budgets
        run: pnpm exec lhci autorun --config=./lighthouserc.json --collect.settings.budgetsPath=./public/lighthouse-budgets.json

      - name: E2E tests
        run: pnpm exec playwright test
        env:
          BASE_URL: http://localhost:4173

      - name: Stop preview server
        if: always()
        run: |
          if [ -f preview.pid ]; then
            kill $(cat preview.pid) || true
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14

      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci/
          retention-days: 14
