name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  typecheck-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run typecheck
      
      - name: Lint
        run: npm run lint
      
      - name: Test with coverage
        run: npm run test -- --coverage --reporter=verbose
      
      - name: Enforce coverage thresholds
        run: |
          # Coverage thresholds are enforced in vitest.config.ts
          # branches: 80%, lines: 85%, statements: 85%, functions: 85%
          echo "✅ Coverage thresholds enforced"
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for secrets
        run: |
          if grep -r "API_KEY\|SECRET\|PASSWORD" --include="*.ts" --include="*.tsx" src/; then
            echo "❌ Found hardcoded secrets"
            exit 1
          fi
          echo "✅ No hardcoded secrets found"
