name: show-your-work

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Validate architecture config
        run: node scripts/validate-architecture.mjs
      
      - name: Validate DB objects (syntactic)
        if: ${{ secrets.DATABASE_URL }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          psql "$DATABASE_URL" -f scripts/validate-db.sql
      
      - name: Validate work-report.json and PR body
        run: node scripts/validate-work-report.mjs
