name: Verify Platform

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Scan features
        run: npm run map
        
      - name: Run platform verification
        run: tsx scripts/verify-platform.ts
        
      - name: Upload manifests
        uses: actions/upload-artifact@v3
        with:
          name: platform-manifests
          path: |
            generated/route-manifest.json
            generated/component-registry.json
            docs/features/features.json
          retention-days: 30
